name: Firebase Hosting CI/CD

on:
  push:
    branches:
      - main  # adjust to your main branch name

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install cross-env
        run: npm install cross-env

      - name: Install webpack-dev-server and eslint globally
        run: |
          sudo npm install -g webpack-dev-server eslint

      - name: Build for production
        run: npm run build-prod

      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          sudo npm install -g firebase-tools
          firebase deploy --only hosting --token "1//0gmT53vjFvtb6CgYIARAAGBASNwF-L9IrbhHWdzUxfVUNqLHPC7dD_U6cPS0jGVtqD64bCIH0wAGsSPXSQgignh-tCW2AuMKWOnY"
