name: Firebase Hosting CI/CD

on:
  push:
    branches:
      - main  # adjust to your main branch name

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Use Node.js version >= 18.0.0 or >= 20.0.0

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Set NODE_ENV to production
        run: export NODE_ENV=production

      - name: Run npm run build-prod
        run: npm run build-prod

      - name: Upgrade Firebase CLI
        run: sudo npm install -g firebase-tools@latest

      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          firebase deploy --only hosting --token "1//0gmT53vjFvtb6CgYIARAAGBASNwF-L9IrbhHWdzUxfVUNqLHPC7dD_U6cPS0jGVtqD64bCIH0wAGsSPXSQgignh-tCW2AuMKWOnY"
